In [1]:
import pandas as pd
import io

csv_data = """Aluno,Portugues,Matematica
Alice,8,9
Bruno,6,7
Carla,7,8
Daniel,5,6
Eduarda,9,10
"""

df = pd.read_csv(io.StringIO(csv_data))
display(df)

     Aluno  Portugues  Matematica
0    Alice          8           9
1    Bruno          6           7
2    Carla          7           8
3   Daniel          5           6
4  Eduarda          9          10

In [2]:
df['Media'] = (df['Portugues'] + df['Matematica']) / 2
display(df)

     Aluno  Portugues  Matematica  Media
0    Alice          8           9    8.5
1    Bruno          6           7    6.5
2    Carla          7           8    7.5
3   Daniel          5           6    5.5
4  Eduarda          9          10    9.5

In [3]:
alunos_aprovados = df[df['Media'] >= 7]
display(alunos_aprovados)

     Aluno  Portugues  Matematica  Media
0    Alice          8           9    8.5
2    Carla          7           8    7.5
4  Eduarda          9          10    9.5